[project]
name = "pyr4t"
version = "0.2.0"
description = ""
authors = [{ name = "R4tL", email = "simon33910.lambert@gmail.com" }]
requires-python = ">=3.13"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "requests>=2.0.0,<3.0.0",
]

[project.optional-dependencies]
dev = ["pytest>=8.3.2", "black>=24.3.0", "isort>=5.13.2"]

[project.scripts]
pyr4t = "pyr4t.luncher:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
